// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WebhookHandler is an autogenerated mock type for the WebhookHandler type
type WebhookHandler struct {
	mock.Mock
}

// ProcessWebhook provides a mock function with given fields: ctx, payload
func (_m *WebhookHandler) ProcessWebhook(ctx context.Context, payload []byte) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for ProcessWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWebhookHandler creates a new instance of WebhookHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookHandler {
	mock := &WebhookHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
